apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-adapter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: prometheus-adapter
  template:
    metadata:
      labels:
        app: prometheus-adapter
    spec:
      serviceAccountName: prometheus-adapter
      containers:
        - name: prometheus-adapter
          image: k8s.gcr.io/prometheus-adapter/prometheus-adapter:v0.10.0
          args:
            - --cert-dir=/tmp
            - --secure-port=6443
            - --logtostderr=true
            - --metrics-relist-interval=1m
            - --config=/etc/adapter/config.yaml
            - --prometheus-url=http://prometheus-server.monitoring.svc.cluster.local
            - --authentication-skip-lookup  # Added to bypass authentication issues
            - --authorization-skip-lookup   # Added to bypass authorization issues
          ports:
            - containerPort: 6443
              name: https
          volumeMounts:
            - name: custom-metrics-config
              mountPath: /etc/adapter
      volumes:
        - name: custom-metrics-config
          configMap:
            name: custom-metrics-config
            items:
              - key: config.yaml
                path: config.yaml
