apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-metrics-config
  namespace: monitoring
data:
  config.yaml: |
    rules:
      - seriesQuery: 'in_flight_requests{namespace="fastapi",pod!=""}'
        resources:
          overrides:
            namespace:
              resource: "namespace"
            pod:
              resource: "pod"
        name:
          matches: "^in_flight_requests$"
        metricsQuery: 'in_flight_requests{namespace="fastapi",pod!=""}'
