prometheus:
  url: http://prometheus-server.monitoring.svc.cluster.local
  port: 80

rules:
  default: false
  custom:
    - seriesQuery: 'in_flight_requests{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: "^(.*)$"
        as: "${1}_per_pod"
      metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)

extraArgs:
- --authentication-skip-lookup
- --authorization-skip-lookup
- --secure-port=6443
- --cert-dir=/tmp
- --logtostderr=true
- --metrics-relist-interval=1m
- --prometheus-url=http://prometheus-server.monitoring.svc.cluster.local

tls:
  enabled: true
  generate: true

apiService:
  caBundle: ""

service:
  ports:
  - name: https
    port: 443
    targetPort: 6443

containerPorts:
- name: https
  containerPort: 6443
